# Generated by Django 4.2.9 on 2024-07-29 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=120)),
                ('hotel_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=120)),
                ('amenity', models.ManyToManyField(to='hotels.amenity')),
            ],
        ),
    ]
