# Generated by Django 4.2.9 on 2024-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
