# Generated by Django 4.2.9 on 2024-08-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id',
            new_name='review_uuid',
        ),
    ]
